language: node_js
node_js:
  - "5"
  - "6"
after_script:
  - NODE_ENV=test istanbul cover `npm bin`/_mocha --report lcovonly -- -R spec --compilers js:babel-register && cat ./coverage/lcov.info | `npm bin`/coveralls && rm -rf ./coverage
